const games = [
    { title: "1v1.LOL", url: "1v1-lol.html", category: "Action", image: "1v1.lol.png" },
    { title: "2048", url: "2048.html", category: "Puzzle", image: "2048.png" },
    { title: "Among Us", url: "among-us.html", category: "Multiplayer", image: "Among Us.png" },
    { title: "Chess", url: "chess.html", category: "Strategy", image: "Chess.png" },
    { title: "Cluster Rush", url: "cluster-rush.html", category: "Skill", image: "Cluster Rush.png" },
    { title: "Cookie Clicker", url: "cookie-clicker.html", category: "Simulation", image: "Cookie Clicker.png" },
    { title: "Death Run 3D", url: "death-run-3d.html", category: "Skill", image: "Death Run 3D.png" },
    { title: "Drift Boss", url: "drift-boss.html", category: "Driving", image: "Drift Boss.png" },
    { title: "Drive Mad", url: "drive-mad.html", category: "Driving", image: "Drive Mad.png" },
    { title: "Eaglercraft", url: "eaglercraft.html", category: "Sandbox", image: "Eaglercraft.png" },
    { title: "Elastic Man", url: "elastic-man.html", category: "Funny", image: "Elastic Man.png" },
    { title: "Epic Ninja", url: "epic-ninja.html", category: "Action", image: "Epic Ninja.png" },
    { title: "Fireboy and Watergirl Forest Temple", url: "fireboy-and-watergirl.html", category: "Puzzle", image: "Fireboy and Watergirl Forest Temple.png" },
    { title: "Five Nights at Freddy's", url: "five-nights-at-freddys.html", category: "Horror", image: "Five Nights at Freddy's.png" },
    { title: "Flappy Bird", url: "flappy-bird.html", category: "Arcade", image: "Flappy Bird.png" },
    { title: "G-Switch 3", url: "g-switch-3.html", category: "Skill", image: "G-Switch 3.png" },
    { title: "Geometry Dash", url: "geometry-dash.html", category: "Arcade", image: "Geometry Dash.png" },
    { title: "Getting Over it", url: "getting-over-it.html", category: "Skill", image: "Getting Over it.png" },
    { title: "Google Doodle Baseball", url: "google-doodle-baseball.html", category: "Sports", image: "Google Doodle Baseball.png" },
    { title: "Google Gravity", url: "google-gravity.html", category: "Funny", image: "Google Gravity.png" },
    { title: "Google Santa Tracker", url: "google-santa-tracker.html", category: "Holiday", image: "Google Santa Tracker.png" },
    { title: "Google Space", url: "google-space.html", category: "Funny", image: "Google Space.png" },
    { title: "Gun Spin", url: "gun-spin.html", category: "Action", image: "Gun Spin.png" },
    { title: "Happy Wheels", url: "happy-wheels.html", category: "Funny", image: "Happy Wheels.png" },
    { title: "Henry Stickman Escaping the Prison", url: "henry-stickman.html", category: "Adventure", image: "Henry Stickman Escaping the Prison.png" },
    { title: "Hobo Simulator", url: "hobo-simulator.html", category: "Simulation", image: "Hobo Simulator.png" },
    { title: "Idle Miner Tycoon", url: "idle-miner-tycoon.html", category: "Simulation", image: "Idle Miner Tycoon.png" },
    { title: "Jelly Mario", url: "jelly-mario.html", category: "Funny", image: "Jelly Mario.png" },
    { title: "JustFall.LOL", url: "justfall-lol.html", category: "Multiplayer", image: "JustFall.LOL.png" },
    { title: "Low's Adventure", url: "lows-adventure.html", category: "Adventure", image: "Low's Adventure.png" },
    { title: "Low's Adventure 2", url: "lows-adventure-2.html", category: "Adventure", image: "Low's Adventure 2.png" },
    { title: "Maze", url: "maze.html", category: "Puzzle", image: "Maze.png" },
    { title: "Monkey Mart", url: "monkey-mart.html", category: "Simulation", image: "Monkey Mart.png" },
    { title: "Moto X3M", url: "moto-x3m/moto-x3m.html", category: "Driving", image: "moto-x3m/Moto X3M.png" },
    { title: "Pac-Man", url: "pac-man.html", category: "Arcade", image: "Pac-Man.png" },
    { title: "Paper Flight", url: "paper-flight.html", category: "Skill", image: "Paper Flight.png" },
    { title: "Plants VS Zombies", url: "plants-vs-zombies.html", category: "Strategy", image: "Plants VS Zombies.png" },
    { title: "Powerline.io", url: "powerline-io.html", category: "Multiplayer", image: "Powerline.io.png" },
    { title: "Retro Bowl", url: "retro-bowl.html", category: "Sports", image: "Retro Bowl.png" },
    { title: "Run 3", url: "run-3.html", category: "Skill", image: "Run 3.png" },
    { title: "Snake.io", url: "snake-io.html", category: "Multiplayer", image: "Snake.io.png" },
    { title: "Slope", url: "slope.html", category: "Skill", image: "Slope.png" },
    { title: "Stickman Hook", url: "stickman-hook.html", category: "Skill", image: "Stickman Hook.png" },
    { title: "Subway Surfers", url: "subway-surfers.html", category: "Arcade", image: "Subway Surfers.png" },
    { title: "Super Mario Bros", url: "super-mario-bros.html", category: "Platformer", image: "Super Mario Bros.png" },
    { title: "Tax Fraud Simulator", url: "tax-fraud-simulator.html", category: "Simulation", image: "Tax Fraud Simulator.png" },
    { title: "Tax Fraud Simulator 2", url: "tax-fraud-simulator-2.html", category: "Simulation", image: "Tax Fraud Simulator 2.png" },
    { title: "Terraria", url: "terraria.html", category: "Sandbox", image: "Terraria.png" },
    { title: "The Impossible Quiz", url: "the-impossible-quiz.html", category: "Puzzle", image: "The Impossible Quiz.png" },
    { title: "There Is No Game", url: "there-is-no-game.html", category: "Puzzle", image: "There Is No Game.png" },
    { title: "Tomb of the Mask", url: "tomb-of-the-mask.html", category: "Arcade", image: "Tomb of the Mask.png" },
    { title: "Tunnel Rush", url: "tunnel-rush.html", category: "Skill", image: "Tunnel Rush.png" },
    { title: "Vex", url: "vex/vex.html", category: "Platformer", image: "vex/Vex.png" },
    { title: "We Become What We Behold", url: "we-become-what-we-behold.html", category: "Funny", image: "We Become What We Behold.png" },
    { title: "Zombie Last Survivor", url: "zombie-last-survivor.html", category: "Action", image: "Zombie Last Survivor.png" }
]; 